### PR TITLE
Consistent spacing in python/tutorial.ipynb

### PR DESCRIPTION
**Pull request by fanminshi**
Improve inconsistency of grouping variables between code blocks.

### CODE REVIEW

**Comment by yuvaltassa** [comment]
Nice!
Can you do the CLA thing please? Thanks!

**Comment by fanminshi** [comment]
@yuvaltassa yep i did the CLA thing!

**Comment by fanminshi** [comment]
@yuvaltassa is the CL ready to be merged? I have other CLs to be submited after this. I find few improvments on style for this tutorials.

**Comment by yuvaltassa** [comment]
Thanks for the reminder, I'll get on it 🙂

**Comment by yuvaltassa** [comment]
Something funny with importing this, can you try syncing to head please?

**Comment by fanminshi** [comment]
@yuvaltassa i rebased this commit against main. let me know if it works on yourside now.

**Review by yuvaltassa — APPROVED** [review]

**Comment by yuvaltassa** [comment]
Okay this is now at head, thanks so much @fanminshi !

One thing that we probably need to do is change all uses of `Renderer` to use the [context manager format](https://github.com/google-deepmind/mujoco/blob/64cd44252fdf73d289970ff9fb2bc4c6a845850f/python/mujoco/renderer_test.py#L51), people keep tripping up on `Renderer` instances hanging around e.g. #1185 ...

Future PRs to notebooks should get pulled in much quicker, I needed to sort some issues on our end

**Comment by fanminshi** [comment]
great thanks!

**Pull request merged**
