### PR TITLE
Fix mj forward link

### PR DESCRIPTION
**Pull request by alefram**
fix mj_forward reference link on tutorial

### CODE REVIEW

**Review by yuvaltassa — CHANGES_REQUESTED** [review]
Why does the diff look like this?
PR description sounds like a 1 line change?

**Comment by alefram** [comment]
Hi , yes, I just changed the link for mj_forward. I don't understand why it appears differently. I made the changes locally, meaning I ran Jupyter Lab on my local machine and then made the change.

**Comment by alefram** [comment]
@yuvaltassa

**Comment by alefram** [comment]
I will fix it and send it again maybe when I run it change the metadata.

**Comment by yuvaltassa** [comment]
I recommend just doing the edit in a plain text editor. When you load the notebook all sorts of things happen to the file...

**Comment by alefram** [comment]
Thank you @yuvaltassa I will do it next time.

**Review by yuvaltassa — APPROVED** [review]

**Pull request merged**
