### PR TITLE
[Unity plugin] Remove sensor noise properties

### PR DESCRIPTION
**Pull request by Balint-H**
Remove references in MjGlobalOptions and sensor base class to the deprecated sensornoise attribute.

### CODE REVIEW

**Review by yuvaltassa — COMMENTED** [review]
Removing the enable flag: Great!

Removing the sensor attribute: Why? It's still there for the user to write into, if they like... Maybe just update the tooltip?

**Comment by Balint-H** [comment]
I think it could be easily misleading, e.g. they have learned some RL controller but want to make it more robust with sensor noise, they see the option and just put a value there without it actually having the intended effect. In any component they use to collect sensor readings with, they can inject noise there just as well.

**Review by erez-tom — APPROVED** [review]

**Comment by erez-tom** [comment]
Could you please run the tests?  Both MjBaseSensorTests and MjcfImporterTests make references to this now-absent field.

**Comment by Balint-H** [comment]
Somehow I missed the test framework implementation in the package (by default it is not compiled)! From now on I'll make sure to run them before a PR, and I'll amend this one.

**Review by erez-tom — APPROVED** [review]

**Pull request merged**
