### PR TITLE
Draft of multithreaded minimize.py and more verbose logging

### PR DESCRIPTION
**Pull request by aftersomemath**
I've started using `minimize.py` for sysid, and it is working well!

This draft hacks `minimize.py` to support parallel jacobian estimation (in one case) and some WIP tweaks to the logging that make it easier to tune the mu parameters. On my problem this results in a 4.2x speedup and I think we can squeeze out a bit more without any real downsides.

If any subset of these changes sounds promising I would be happy to make a feature complete version for merging. I need this kind of parallelism for my work anyway. I'll probably also be looking into speculative multi-threaded line searches soon.

Below is an example of the speedup and logging changes:
```
Single thread
iter: 0    y: 3.418      log10mu: -1.0  ratio: 1.5      dx: 0.49     reduction: 1.5      Res evals: 2  Jac res evals 25  Jac evals 1  time: 25.8
iter: 1    y: 1.894      log10mu: -1.0  ratio: 0.068    dx: 0.81     reduction: 0.04     Res evals: 1  Jac res evals 25  Jac evals 1  time: 25.7
iter: 2    y: 1.854      log10mu: -0.7  ratio: 0.4      dx: 0.61     reduction: 0.2      Res evals: 1  Jac res evals 25  Jac evals 1  time: 25.8
iter: 3    y: 1.65       log10mu: -0.7  ratio: 0.6      dx: 0.23     reduction: 0.12     Res evals: 1  Jac res evals 25  Jac evals 1  time: 25.6
iter: 4    y: 1.525      log10mu: -0.7  ratio: 1.3      dx: 0.1      reduction: 0.095    Res evals: 1  Jac res evals 25  Jac evals 1  time: 25.5
iter: 5    y: 1.431      log10mu: -1.0  ratio: 5.1      dx: 0.0049   reduction: 0.0039   Res evals: 1  Jac res evals 25  Jac evals 1  time: 25.5
iter: 6    y: 1.427      log10mu: -1.0  ratio: 1.2e+02  dx: 0.0016   reduction: 0.0084   Res evals: 1  Jac res evals 25  Jac evals 1  time: 25.4
iter: 7    y: 1.418      log10mu: -1.0  ratio: 1.5      dx: 0.0028   reduction: 0.00088  Res evals: 1  Jac res evals 25  Jac evals 1  time: 25.4
iter: 8    y: 1.417      log10mu:  2.3  ratio: 75       dx: 0.00047  reduction: 0.0041   Res evals: 12  Jac res evals 25  Jac evals 1  time: 36.3
iter: 9    y: 1.413      log10mu:  5.0  ratio: 75       dx: 1.4e-06  reduction: -0.0041  Res evals: 11  Jac res evals 25  Jac evals 1  time: 35.6
Terminated after 9 iterations: insufficient reduction. y: 1.413, Residual evals: 32, Jacobian residual evals: 250, Jacobian evals: 10
total time 277.5s of which residual 11.4% Jacobian 88.6%


Multithread
iter: 0    y: 3.418      log10mu: -1.0  ratio: 1.5      dx: 0.49     reduction: 1.5      Res evals: 2  Jac res evals 25  Jac evals 1  time: 4.0
iter: 1    y: 1.894      log10mu: -1.0  ratio: 0.068    dx: 0.81     reduction: 0.04     Res evals: 1  Jac res evals 25  Jac evals 1  time: 4.4
iter: 2    y: 1.854      log10mu: -0.7  ratio: 0.4      dx: 0.61     reduction: 0.2      Res evals: 1  Jac res evals 25  Jac evals 1  time: 4.2
iter: 3    y: 1.65       log10mu: -0.7  ratio: 0.6      dx: 0.23     reduction: 0.12     Res evals: 1  Jac res evals 25  Jac evals 1  time: 4.5
iter: 4    y: 1.525      log10mu: -0.7  ratio: 1.3      dx: 0.1      reduction: 0.095    Res evals: 1  Jac res evals 25  Jac evals 1  time: 4.4
iter: 5    y: 1.431      log10mu: -1.0  ratio: 5.1      dx: 0.0049   reduction: 0.0039   Res evals: 1  Jac res evals 25  Jac evals 1  time: 4.5
iter: 6    y: 1.427      log10mu: -1.0  ratio: 1.2e+02  dx: 0.0016   reduction: 0.0084   Res evals: 1  Jac res evals 25  Jac evals 1  time: 4.5
iter: 7    y: 1.418      log10mu: -1.0  ratio: 1.5      dx: 0.0028   reduction: 0.00088  Res evals: 1  Jac res evals 25  Jac evals 1  time: 4.4
iter: 8    y: 1.417      log10mu:  2.3  ratio: 75       dx: 0.00047  reduction: 0.0041   Res evals: 12  Jac res evals 25  Jac evals 1  time: 15.3
iter: 9    y: 1.413      log10mu:  5.0  ratio: 75       dx: 1.4e-06  reduction: -0.0041  Res evals: 11  Jac res evals 25  Jac evals 1  time: 14.1
Terminated after 9 iterations: insufficient reduction. y: 1.413, Residual evals: 32, Jacobian residual evals: 250, Jacobian evals: 10
total time 65.7s of which residual 48.4% Jacobian 51.5%

```

Total speedup is 4.2x on a problem with ~25 variables, ~60k residuals, rollouts take a second or two each, 24 core cpu, process pool initialized with all data except for optimized variables.

If speculative line searches were implemented in a similar fashion, another ~30% speedup would be achieved on this problem. However, the mu parameters were tuned for this run. If they were not tuned, the speedup might be similar to parallel jacobian estimation.

### CODE REVIEW

**Comment by yuvaltassa** [comment]
Hi Levi, this speedup is nice!

1. The way I was imagining multi-threading would work is using the `jacobian` callback. In other words, if the user wants to, they can pass in a multithreaded callback that will simply run faster. I'm concerned that making the multi-threading internal to the function could have all sorts of unintended consequences. Most importantly, if the user doesn't write the residual function correctly w.r.t GIL locking, they would get no speedup at all.

Here are the upgrades that I was imagining as next steps:

2. Add a built-in, off-by-default option for checking the user-given jacobian against the built in FD. This is important since there would be no other indication other than the optimization not working well (or at all).
3. Add support for norms other than quadratic. This is important for e.g. outlier rejection in sysID. Again I was imagining that the norm would be something the user would pass in, with the default being quadratic. Note that the norm $n$ needs to be able to compute its own gradient and Hessian, as the GN Hessian becomes the sandwich $H = J^T \cdot \nabla^2n \cdot J$.

Let me know your thoughts regarding 1, 2 and 3.

**Comment by yuvaltassa** [comment]
1 - What if we just made the residual function always vectorized? (somewhat of a refactor, but this is new code) That would solve a lot of things, right?
2 and 3 - Good to know.
4 - Can you sketch out what this looks like from the user's perspective?

**Comment by aftersomemath** [comment]
The only issue I see with always vectorized is that it effectively doubles memory usage. All the parameter perturbations and all the corresponding residual vectors will have to be stored in memory at once to be passed to and from a vectorized residual function. I'm not sure if this is a significant drawback, but if so it can be mitigated with a max_vector_size argument or similar.

Related, though not entirely equivalent, SciPy's [`solve_ivp`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html) takes the approach of using a `vectorized` flag. The documentation notes that vectorization is sometimes slower.

Here is a sketch.
```python
def iter_callback(iter_log):
    # Plot or otherwise visualize the contents of iter_log (possibly on a separate process
    # without interrupting the running optimization). This could mean rolling out
    # a simulation with the Python viewer, visualizing the residuals to find
    # trouble areas, etc.
    # The user should handle any details related to multi processing/threading.

xstar, _ = minimize.least_squares(x0, residual, iter_callback=iter_callback)
```

Such visualization can be done after the optimization finishes, but then the user has to wait.

**Comment by yuvaltassa** [comment]
Memory usage is not a concern, in this case. I think vectorized makes sense, I hope to get to it soonish, and the different norms, and Jacobian checking too.

**Comment by aftersomemath** [comment]
Great, thank you!

**Comment by yuvaltassa** [comment]
Note the notebook is broken, will be fixed after this week's release. To run it till then you can pip install from wherever Saran puts the Dev build, he posted a link at some point. @kevinzakka do you remember?

**Comment by aftersomemath** [comment]
Awesome thanks! Just in time too, this was my next blocking issue.

I believe the new bounds reshape semantics are broken. Part of the code assumes bounds is passed in as a NumPy array (uses `.copy`) and a few lines later assumes bounds is a list. The following fixed it:

```python
# Reshape and clip.
bounds_temp = [None, None]
bounds_temp[0] = bounds[0].reshape(n, 1)
bounds_temp[1] = bounds[1].reshape(n, 1)
bounds = bounds_temp
np.clip(x, bounds[0], bounds[1], out=x)
```

**Comment by yuvaltassa** [comment]
What if I replace `bounds = None if bounds is None else bounds.copy()` with `bounds = None if bounds is None else list(bounds)` ?

The way you did it defeats the purpose of the checks under `# Check bounds.`

**Comment by aftersomemath** [comment]
Yes that is better!

**Pull request closed without merging**
