### PR TITLE
Fix the initialization of the EGL context in multiprocessing

### PR DESCRIPTION
**Pull request by squarefk**
**Use Case: Render Multiple Tasks with EGL in Separate Processes**

In the current implementation, the global variable `EGL_DISPLAY` is initialized with the result of `create_initialized_egl_device_display()` as soon as the MuJoCo library is imported (most likely in the main process). This causes issues when users attempt to render multiple tasks in parallel across different processes. Since the initialized EGL state cannot be shared between processes, an error occurs when child processes attempt to render.

To address this, `create_initialized_egl_device_display()` should be invoked separately within each process, ensuring that each process has its own initialized EGL state.

For example, the following code snippet, adapted from [the render test](https://github.com/google-deepmind/mujoco/blob/7a92423cf28700e30b2f4c93e00113ea4ceb2bd2/python/mujoco/render_test.py#L35) and modified to use multiprocessing, will fail under the current implementation:

```
import time
import mujoco
from multiprocessing.context import Process
import numpy as np

def run():
    gl = mujoco.GLContext(640, 480)
    gl.make_current()

    model = mujoco.MjModel.from_xml_string('<mujoco><worldbody/></mujoco>')
    data = mujoco.MjData(model)

    scene = mujoco.MjvScene(model, maxgeom=0)
    mujoco.mjv_updateScene(
        model, data, mujoco.MjvOption(), mujoco.MjvPerturb(),
        mujoco.MjvCamera(), mujoco.mjtCatBit.mjCAT_ALL, scene)

    context = mujoco.MjrContext(model, mujoco.mjtFontScale.mjFONTSCALE_150)
    mujoco.mjr_setBuffer(mujoco.mjtFramebuffer.mjFB_OFFSCREEN, context)

    # MuJoCo's default render buffer size is 640x480.
    full_rect = mujoco.MjrRect(0, 0, 640, 480)
    mujoco.mjr_rectangle(full_rect, 0, 0, 0, 1)

    blue_rect = mujoco.MjrRect(56, 67, 234, 123)
    mujoco.mjr_rectangle(blue_rect, 0, 0, 1, 1)

    expected_upside_down_image = np.zeros((480, 640, 3), dtype=np.uint8)
    expected_upside_down_image[67:67+123, 56:56+234, 2] = 255

    upside_down_image = np.empty((480, 640, 3), dtype=np.uint8)
    mujoco.mjr_readPixels(upside_down_image, None, full_rect, context)
    np.testing.assert_array_equal(upside_down_image, expected_upside_down_image)

    # Check that mjr_readPixels can accept a flattened array.
    upside_down_image[:] = 0
    mujoco.mjr_readPixels(
        np.reshape(upside_down_image, -1), None, full_rect, context)
    np.testing.assert_array_equal(upside_down_image, expected_upside_down_image)
    context.free()

process1 = Process(target=run, daemon=True)
process2 = Process(target=run, daemon=True)
process1.start()
process2.start()
time.sleep(3)
print("Success")
```

### CODE REVIEW

**Comment by squarefk** [comment]
I should have signed the CLA but the check still fails. Any idea?

**Comment by yuvaltassa** [comment]
> I should have signed the CLA but the check still fails. Any idea?

Is the email you signed with the same one that is associated with your GH account?

**Comment by squarefk** [comment]
Yes. I think so.
My github username is: squarefk
My primary email on github is: squarefk@gmail.com

**Comment by yuvaltassa** [comment]
Click on Details above and follow the "Help! I've signed the CLA, but it's still showing me as unsigned." section?

**Comment by squarefk** [comment]
Sorry that I used a wrong email. Thanks for the reminder!

**Comment by yuvaltassa** [comment]
No worries 🙂 
Just a heads up that @saran-t is away until next month, he will look at it then.

Thanks for the contribution!

**Comment by squarefk** [comment]
@saran-t  @yuvaltassa 
Any thoughts/updates regarding this issue?

**Pull request merged**
